export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  RESULT_NOT_ABNORMAL: "RESULT_NOT_ABNORMAL",
  RECTIFY_EVIDENCE_REQUIRED: "RECTIFY_EVIDENCE_REQUIRED",
  RECTIFY_STATUS_FORBIDDEN: "RECTIFY_STATUS_FORBIDDEN",
  DEVICE_HAS_OPEN_HAZARD: "DEVICE_HAS_OPEN_HAZARD",
  INVALID_DEVICE_STATUS: "INVALID_DEVICE_STATUS",
  BACKEND_UNAVAILABLE: "BACKEND_UNAVAILABLE"
} as const;
