export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  INVALID_TICKET_STATE: "INVALID_TICKET_STATE",
  RECTIFY_EVIDENCE_REQUIRED: "RECTIFY_EVIDENCE_REQUIRED",
  DEVICE_BLOCKED_BY_HAZARD: "DEVICE_BLOCKED_BY_HAZARD",
  SUPERVISOR_REQUIRED: "SUPERVISOR_REQUIRED"
} as const;
